[environments.default]
url = "jdbc:postgresql://localhost:5434/db_flyway_repaso"
user = "postgres"
password = "admin123"
schemas = ["public"]

[flyway]
locations = ["filesystem:sql","filesystem:repeatable"]